### ISSUE TITLE
How to change the wording of "xxx GAMES" below each system into something else..

### ISSUE THREAD

**Issue by worstcase-scenario** [anthonycaccese/es-theme-art-book#10]
Hi, I'm from Germany... and I really like your theme and I'm using it all the time and also expanded it by adding new graphics for some systems.  Works great!

Now I also have added amongst the video game systems a movie section, where I have stored 20 mp4's (using mplayer). It works, but of course, the theme settings show "20 GAMES" below the icon, not knowing that there are no games but video files. 

Can I change the word "GAMES" universally into "TITEL" - meaning "ITEMS"-  somehow? 

I already tried to change it manually in the respective DE-language-config folder LC_MESSAGES by altering the files  "emulationstation2.po" and "emulationstation2.po~" like this:

#, c-format
msgid "%i GAME"
msgid_plural "%i GAMES"
msgstr[0] "%i TITEL"
msgstr[1] "%i TITEL"

..., but it still just shows "xxxx GAMES" under each system... 

Are there any other places or files that I haven't found yet where all the strings for the UI are stored and can be altered?

Any help or idea would be appreciated! Thank you!

**Comment by anthonycaccese** [comment]
hi @worstcase-scenario, thank you for writing!  I am sorry I am not sure how to change the text you are trying to change - its unfortunately not something that can be changed via the theme.

**Comment by worstcase-scenario** [comment]
Thanks for the answer. I'll try to ask for help on the variius Emuelec Sites...
