### ISSUE TITLE
Only audio from videos; system video differs from example

### ISSUE THREAD

**Issue by ds8k** [anthonycaccese/es-theme-art-book#2]
I'm running RetroPie 4.2 on a RaspberryPi 3. Just downloaded this theme from the master, extracted to `/home/pi/.emulationstation/themes/` and rebooted. I've scraped NES, Genesis, and Sega CD using the command in the README, which appears to have worked except that there's no video. It's definitely playing a video, as I can hear the audio from it, but I only get a black box on the screen where the video should be.

Also my System view is very different. Kinda just looks like the Carbon theme but with a grey background behind the system names.

**Comment by ds8k** [comment]
Welp, this is totally on me. Did more research and found that my version of Emulation Station needed to be updated.

**Comment by anthonycaccese** [comment]
@ds8k thank you for letting me know that updating solved it.  If you see anything else don't hesitate to send me the details.
