### ISSUE TITLE
Any plan to update to the new ES?

### ISSUE THREAD

**Issue by chrilith** [anthonycaccese/es-theme-art-book#3]
Hi!

I really love your theme and I was wondering if you plan to update it to the latest ES version which features many new features: UI, region settings, different background colours, different button set and so on.

Would be also nice if you could add some new system supported by RetroPie and Recalbox (systems list here: https://gitlab.com/recalbox/recalbox-themes/tree/master/themes/recalbox)

Keep up the great work!
Thanks
Chris

**Comment by anthonycaccese** [comment]
Hi @chrilith, so sorry for my delay in responding.  I have plans to add support for kiosk and kids mode.  Likely not going to do background colors as the box art is meant to be the main focal point in the theme.  I haven't heard about region settings changes so I need to look that up.  Are there any other specific settings you think it would be cool for me to check out?

I'll scrub the recalbox list as well and make sure to add any missing systems.  Thank you for checking out the theme and giving me a heads up on new features!

**Comment by chrilith** [comment]
Hi, no problem :)

Well, I really don't know about other features, I saw that the menu can also be customize (it is different when using your theme). Better to check the official [Recalbox themes](https://gitlab.com/recalbox/recalbox-themes) and see what 's new in the XMLs.

Thx
