### ISSUE TITLE
How to remove video border...?

### ISSUE THREAD

**Issue by worstcase-scenario** [anthonycaccese/es-theme-art-book#8]
Hi, your theme is great, the only one I'm using.... 
But I have a question: As not every game has a videosnap, the theme then shows the static.mp4  (if there's another game on the list with a gamesnap-video). When there's only a boxart/screenshot but no gamevideo, I want the theme to only show the image but not the video-window in the corner with the static.mp4-video. I already made a new static.mp4-video that shows only the grey background color (#cccccc). But there's still a thin border around the video. Is it somehow possible to remove that small frame around the videoscreen? 
Thanks!

**Comment by anthonycaccese** [comment]
Yes if you are ok with editing the theme manually this should do what you are looking for...

Look at these lines of XML in theme.xml
```
<view name="video">
      <image name="md_marquee">
         <origin>0 0</origin>
         <pos>1 1</pos>
      </image>
      <image name="video-background" extra="true">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <size>0.25625 0.3444444444444444</size>
         <path>./_inc/images/space.png</path>
         <color>bbbbbb</color>
      </image>
      <image name="video-screen" extra="true">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <size>0.25 0.3333333333333333</size>
         <path>./_inc/images/space.png</path>
         <color>000000</color>
      </image>
      <video name="md_video">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <maxSize>0.25 0.3333333333333333</maxSize>
         <delay>0</delay>
         <default>./_inc/videos/static.mp4</default>
         <showSnapshotNoVideo>false</showSnapshotNoVideo>
         <showSnapshotDelay>false</showSnapshotDelay>
      </video>
   </view>
```

Remove these...
```
<image name="video-background" extra="true">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <size>0.25625 0.3444444444444444</size>
         <path>./_inc/images/space.png</path>
         <color>bbbbbb</color>
      </image>
      <image name="video-screen" extra="true">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <size>0.25 0.3333333333333333</size>
         <path>./_inc/images/space.png</path>
         <color>000000</color>
      </image>
```

Afterward the video section should look like this...
```
<view name="video">
      <image name="md_marquee">
         <origin>0 0</origin>
         <pos>1 1</pos>
      </image>
      <video name="md_video">
         <origin>0.5 0.5</origin>
         <pos>0.540625 0.705555555555556</pos>
         <maxSize>0.25 0.3333333333333333</maxSize>
         <delay>0</delay>
         <default>./_inc/videos/static.mp4</default>
         <showSnapshotNoVideo>false</showSnapshotNoVideo>
         <showSnapshotDelay>false</showSnapshotDelay>
      </video>
   </view>
```

**Comment by worstcase-scenario** [comment]
Hi, thanks for the answer. I edited the theme.xml, but unfortunately there's still a small frame... I made two fotos of the screen...

![20210523_165158](https://user-images.githubusercontent.com/83265453/119265788-3b804180-bbe8-11eb-8f30-01049638ad51.jpg)


![20210523_165206](https://user-images.githubusercontent.com/83265453/119265707-f2c88880-bbe7-11eb-8c6a-8238db1337b9.jpg)

**Comment by worstcase-scenario** [comment]
Solved it. I just had to rename the static.mp4-file (into oldstatic.mp4), now there's no more border... I guess the same thing would happen if one erases the mp4-file... thanks again for the feedback!
