### ISSUE TITLE
Hiding empty/unneeded widgets during scroll

### ISSUE THREAD

**Issue by chcore** [anthonycaccese/es-theme-art-book#9]
Hello, this skin is beautiful. It's just slightly less beautiful while you are scrolling a large list continuously. There is a black box for the video (with no video playing), a line that separates art and plot (even though there is no art or plot) and button prompts to launch or favourite (we're scrolling, so we can't really favourite or launch anything right now).

Would it be possible to hide all of the above elements when we are scrolling through the list, and possibly replace them with e.g. some elegant 'Loading' text? Thanks!

**Comment by anthonycaccese** [comment]
That unfortunately isn’t possible as EmulationStation does not support that
